on:
  push:
    branches:
    - main
jobs:
   build:
     name: Build for ${{ matrix.os }}
     runs-on: ${{ matrix.os }}

     strategy:
          matrix:
              os: [ubuntu-latest, windows-latest, macos-latest]
              buildPath: [./build/main/ivaTools, ./build/main/ivaTools.exe, ./build/main/ivaTools.app]
     steps:
        - name: Install Dependencies
          run: pip install -r requirements.txt
      
        - name: Install PyInstaller
          run: pip install pyInstaller

        - name: Package it all up
          run: python -m PyInstaller main.spec

        - name: Upload Linux
          uses: actions/upload-artifact@v3.1.3
          if: matrix.os == 'ubuntu-latest'
          with:
            name: linux
            path: ./build/main/ivaTools
        - name: Upload Windows
          uses: actions/upload-artifact@v3.1.3
          if: matrix.os == 'windows-latest'
          with:
            name: windows
            path: ./build/main/ivaTools.exe
        - name: Upload MacOS
          uses: actions/upload-artifact@v3.1.3
          if: matrix.os == 'macos-latest'
          with:
            name: macOS
            path: ./build/main/ivaTools.app
            
   release:
        runs-on: ubuntu-latest
        needs: [build]
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - uses: actions/download-artifact@v3
            with:
              name: linux
              path: builds
    
          - uses: actions/download-artifact@v3
            with:
              name: macOS
              path: builds
    
          - uses: actions/download-artifact@v3
            with:
              name: windows
              path: builds
              
          - run: gh release upload release --clobber builds/*
          
        env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
                
              
            
